version: "3"

tasks:
  build:
    cmds:
      - mkdir -p dist/
      - go build -o ./dist/rayt
    silent: true

  run:
    cmds:
      - ./dist/rayt > image.ppm
      - open ./image.ppm
    silent: true
